server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: admin
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Order Management Service