version: '2'

services:
  order-java-task:
    image: 'order-java-task:latest'
    build:
      context: .
    container_name: order-java-task
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
       - 'POSTGRES_DB=orderdb'
       - 'POSTGRES_USER=admin'
       - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432'
volumes:
  postgres-data: